### ISSUE TITLE
VPN connection is disconnecting after 10~20 min connected automatically

### ISSUE THREAD

**Issue by Saeed118** [passepartoutvpn/tunnelkit#209] opened 2021-07-03 08:34 UTC
VPN connection was success, initially.
(TCP, UDP, TLS WRAP).
After 10~20 min, VPN is disconnecting automatically,
What is the reason?
IPHONE keep unlock status for 20 min.
Hope you help me!!!
Thanks

**Comment by keeshux** [comment] 2021-11-05 10:35
So the VPN is disconnecting 10-20min after unlocking the phone, correct?

Duplicate of https://github.com/passepartoutvpn/tunnelkit/issues/138

**Closed by keeshux** 2021-11-05 10:35 UTC
